# Blog Configuration
site:
  title: 'ilham alfath blog'
  description: 'Ilham Alfath personal blog - sharing thoughts on technology, development, and digital experiences'
  author: 'ilham alfath'
  email: 'ilham@xpqx.xyz'
  url: 'https://blog.xpqx.xyz'
  language: 'en'

# Build settings
build:
  input_dir: 'content'
  output_dir: 'output'
  template_dir: 'content/templates'
  static_dir: 'content/static'
  posts_per_page: 10
  date_format: '%Y-%m-%d'
  timezone: 'UTC'

# RSS settings
rss:
  enabled: true
  title: 'Ilham Alfath blog RSS Feed'
  description: 'Latest posts from Ilham Alfath blog'
  max_items: 20

# Development settings
dev:
  host: 'localhost'
  port: 8000
  watch: true
  livereload: false

# Asset processing
assets:
  minify_css: true
  minify_js: true
  minify_html: true
  optimize_images: true
  image_quality: 85
  use_hash: true
